name: Release Stable
on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.head_ref }}

      - name: Configure Git
        run: |
          git config --global user.email "omer.moradd@gmail.com"
          git config --global user.name "$GITHUB_ACTOR"

      - name: Lerna Init
        run: lerna bootstrap

      - name: Build
        run: yarn build

      - name: Release
        run: |
          lerna version --conventional-commits --conventional-graduate --create-release github --yes
          lerna publish from-package --yes